In [2]:
import pandas as pd

/Users/aidanwiteck/anaconda3/lib/python3.7/site-packages/pandas/compat/_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)

In [5]:
df = pd.read_csv(
    "../data/final_tables/composite/composite.csv"
)

# One-hot encode the 'month', 'day_of_week', 'hour', and 'Region' columns
categorical_columns = ["year", "month", "day", "day_of_week", "hour", "Region"]
# Step 1: Before encoding, retrieve the unique values for each categorical variable
unique_values_per_categorical_column = {
    col: df[col].unique() for col in categorical_columns
}
df = pd.get_dummies(df, columns=categorical_columns)

In [6]:
df

,timestamp,Demand (MWh),Demand Forecast (MWh),Net Generation (MWh),Normalized Demand,Normalized Forecast,temperature,humidity,cloudcover,windspeed,...,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,Region_banc,Region_erco,Region_isne
0,2016-01-01 00:00:00,1922.0,1910.0,1266.0,-0.139874,-0.162466,0.7,72,0,11.4,...,0,0,0,0,0,0,0,1,0,0
1,2016-01-01 01:00:00,1849.0,1790.0,1271.0,-0.277310,-0.388389,0.6,68,3,12.2,...,0,0,0,0,0,0,0,1,0,0
2,2016-01-01 02:00:00,1795.0,1720.0,1198.0,-0.378975,-0.520177,0.5,65,1,9.1,...,0,0,0,0,0,0,0,1,0,0
3,2016-01-01 03:00:00,1757.0,1698.0,1174.0,-0.450517,-0.561596,0.4,62,8,10.6,...,0,0,0,0,0,0,0,1,0,0
4,2016-01-01 04:00:00,1744.0,1678.0,1146.0,-0.474992,-0.599250,0.3,61,16,11.4,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184102,2022-12-31 20:00:00,13363.0,13470.0,10506.0,-0.141978,-0.101069,7.8,100,100,8.1,...,0,0,0,1,0,0,0,0,0,1
184103,2022-12-31 21:00:00,12770.0,12840.0,10124.0,-0.368696,-0.341934,7.4,100,90,6.6,...,0,0,0,0,1,0,0,0,0,1
184104,2022-12-31 22:00:00,12376.0,12290.0,10325.0,-0.519333,-0.552213,7.1,100,92,7.4,...,0,0,0,0,0,1,0,0,0,1
184105,2022-12-31 23:00:00,11510.0,11660.0,9579.0,-0.850426,-0.793077,7.4,100,97,9.7,...,0,0,0,0,0,0,1,0,0,1
184106,2023-01-01 00:00:00,10922.0,10910.0,9004.0,-1.075233,-1.079821,7.2,100,100,8.2,...,0,0,0,0,0,0,0,0,0,1

In [11]:
input_vars = ["hour_14", "temperature"]
print(df[input_vars].dtypes)

hour_14          uint8
temperature    float64
dtype: object